// Activity dataset for Bored.
// Fields: id, text, minMinutes (time needed), cost: 'free'|'low'|'paid',
// energy: 'low'|'med'|'high', location: 'indoor'|'outdoor'|'any', tags: string[]
const ACTIVITIES = [
  { id: 1, text: "Write down 3 things you're avoiding, then do the smallest one.", minMinutes: 5, cost: 'free', energy: 'low', location: 'any', tags: ['productivity'] },
  { id: 2, text: "Learn to say 'thank you' in a language you don't speak.", minMinutes: 5, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 3, text: "Do a 5-minute stretch: neck, shoulders, hips, hamstrings.", minMinutes: 5, cost: 'free', energy: 'med', location: 'any', tags: ['physical'] },
  { id: 4, text: "Text someone you haven't spoken to in 6+ months.", minMinutes: 5, cost: 'free', energy: 'low', location: 'any', tags: ['social'] },
  { id: 5, text: "Declutter one drawer completely.", minMinutes: 15, cost: 'free', energy: 'med', location: 'indoor', tags: ['chores'] },
  { id: 6, text: "Sketch the object nearest to you, badly, on purpose.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['creative'] },
  { id: 7, text: "Go for a walk with no destination for 15 minutes.", minMinutes: 15, cost: 'free', energy: 'med', location: 'outdoor', tags: ['physical', 'relaxation'] },
  { id: 8, text: "Cook something you've never made before using only what's in your kitchen.", minMinutes: 30, cost: 'free', energy: 'med', location: 'indoor', tags: ['creative', 'chores'] },
  { id: 9, text: "Read the Wikipedia 'On this day' page and pick a rabbit hole.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 10, text: "Do 20 push-ups (or a modified version). Rest 1 min. Do 20 more.", minMinutes: 10, cost: 'free', energy: 'high', location: 'any', tags: ['physical'] },
  { id: 11, text: "Write a one-star review of your own life as if it were a hotel. Make it funny.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['creative'] },
  { id: 12, text: "Call a family member and ask them a question you've never asked.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['social'] },
  { id: 13, text: "Reorganize your desktop/downloads folder into actual folders.", minMinutes: 20, cost: 'free', energy: 'med', location: 'indoor', tags: ['chores', 'productivity'] },
  { id: 14, text: "Learn 5 new words in a language you're studying (or start one).", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 15, text: "Do a 20-minute yoga video for beginners.", minMinutes: 20, cost: 'free', energy: 'med', location: 'indoor', tags: ['physical', 'relaxation'] },
  { id: 16, text: "Write a letter to your future self, one year from now. Set a reminder to reread it.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['creative', 'reflection'] },
  { id: 17, text: "Go outside and name 5 plants or birds you can see. Look up any you don't know.", minMinutes: 15, cost: 'free', energy: 'low', location: 'outdoor', tags: ['learning', 'relaxation'] },
  { id: 18, text: "Meal-prep lunch for tomorrow.", minMinutes: 30, cost: 'low', energy: 'med', location: 'indoor', tags: ['chores'] },
  { id: 19, text: "Try a 10-minute guided meditation.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['relaxation'] },
  { id: 20, text: "Fix one small annoying thing in your home you've been ignoring.", minMinutes: 20, cost: 'low', energy: 'med', location: 'indoor', tags: ['chores'] },
  { id: 21, text: "Watch a documentary trailer list and commit to watching one this week.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 22, text: "Go to a park and just sit for 20 minutes without your phone.", minMinutes: 20, cost: 'free', energy: 'low', location: 'outdoor', tags: ['relaxation'] },
  { id: 23, text: "Write a haiku about your current mood.", minMinutes: 5, cost: 'free', energy: 'low', location: 'any', tags: ['creative'] },
  { id: 24, text: "Do a 30-minute bike ride or run.", minMinutes: 30, cost: 'free', energy: 'high', location: 'outdoor', tags: ['physical'] },
  { id: 25, text: "Teach yourself a magic trick or a card shuffle technique.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['learning', 'creative'] },
  { id: 26, text: "Plan a day trip you'd actually want to take, even if you don't go yet.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['creative', 'reflection'] },
  { id: 27, text: "Deep clean your keyboard/phone/most-touched surface.", minMinutes: 10, cost: 'free', energy: 'low', location: 'indoor', tags: ['chores'] },
  { id: 28, text: "Try to name all the countries in a continent, then check your answers.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 29, text: "Visit a coffee shop or park you've never been to before.", minMinutes: 30, cost: 'low', energy: 'med', location: 'outdoor', tags: ['adventure'] },
  { id: 30, text: "Write down your 5-year plan in one paragraph. Don't overthink it.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['reflection'] },
  { id: 31, text: "Learn a new keyboard shortcut set for a tool you use daily.", minMinutes: 10, cost: 'free', energy: 'low', location: 'indoor', tags: ['productivity', 'learning'] },
  { id: 32, text: "Do a wall-sit for as long as you can, three times.", minMinutes: 10, cost: 'free', energy: 'high', location: 'any', tags: ['physical'] },
  { id: 33, text: "Look through old photos and pick your favorite from each of the last 5 years.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['reflection'] },
  { id: 34, text: "Write a short review of the last book, show, or game you finished.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['creative', 'reflection'] },
  { id: 35, text: "Take a cold shower and time how long you can handle it.", minMinutes: 5, cost: 'free', energy: 'high', location: 'indoor', tags: ['physical'] },
  { id: 36, text: "Draft an email you've been putting off. You don't have to send it yet.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['productivity'] },
  { id: 37, text: "Learn the rules of a board or card game you've never played.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 38, text: "Do a full-body 15-minute HIIT workout video.", minMinutes: 15, cost: 'free', energy: 'high', location: 'indoor', tags: ['physical'] },
  { id: 39, text: "Buy yourself something small and unnecessary that will make today better.", minMinutes: 20, cost: 'paid', energy: 'low', location: 'any', tags: ['adventure'] },
  { id: 40, text: "Try a new restaurant or cuisine you've never had.", minMinutes: 60, cost: 'paid', energy: 'low', location: 'outdoor', tags: ['adventure'] },
  { id: 41, text: "Go to a museum or gallery, even a small local one.", minMinutes: 60, cost: 'low', energy: 'med', location: 'outdoor', tags: ['adventure', 'learning'] },
  { id: 42, text: "Organize your notes app or to-do list into a system that actually works.", minMinutes: 30, cost: 'free', energy: 'med', location: 'indoor', tags: ['productivity'] },
  { id: 43, text: "Write the outline of a story, essay, or blog post idea you've had.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['creative'] },
  { id: 44, text: "Do a 20-minute dance session to a playlist you love. No one is watching.", minMinutes: 20, cost: 'free', energy: 'high', location: 'indoor', tags: ['physical', 'creative'] },
  { id: 45, text: "Look up one skill adjacent to your job that you don't have yet, and read about it.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['learning', 'productivity'] },
  { id: 46, text: "Give away or donate 5 items you haven't used in a year.", minMinutes: 20, cost: 'free', energy: 'med', location: 'indoor', tags: ['chores'] },
  { id: 47, text: "Plan and cook a proper meal from scratch, no shortcuts.", minMinutes: 60, cost: 'low', energy: 'med', location: 'indoor', tags: ['chores', 'creative'] },
  { id: 48, text: "Journal about the best part of your week so far.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['reflection'] },
  { id: 49, text: "Try a new stretch routine targeting the area that's tightest right now.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['physical', 'relaxation'] },
  { id: 50, text: "Look up a hiking trail nearby and go, even a short one.", minMinutes: 60, cost: 'free', energy: 'high', location: 'outdoor', tags: ['physical', 'adventure'] },
  { id: 51, text: "Write down every idea you've had this month that you never acted on.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['reflection', 'creative'] },
  { id: 52, text: "Practice a musical instrument you own but rarely touch.", minMinutes: 20, cost: 'free', energy: 'low', location: 'indoor', tags: ['creative'] },
  { id: 53, text: "Do 3 sets of squats, lunges, and planks.", minMinutes: 15, cost: 'free', energy: 'high', location: 'any', tags: ['physical'] },
  { id: 54, text: "Find a local event happening this week and consider going.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['social', 'adventure'] },
  { id: 55, text: "Watch a video essay or long-form talk on something outside your usual interests.", minMinutes: 30, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 56, text: "Wash your car, bike, or another neglected possession.", minMinutes: 30, cost: 'low', energy: 'med', location: 'outdoor', tags: ['chores'] },
  { id: 57, text: "Draft a 'not-to-do' list: 3 habits you want to stop this month.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['reflection', 'productivity'] },
  { id: 58, text: "Take yourself on a solo coffee or ice cream date.", minMinutes: 30, cost: 'low', energy: 'low', location: 'outdoor', tags: ['relaxation', 'adventure'] },
  { id: 59, text: "Fix your sleep setup: set tomorrow's alarm and lay out clothes tonight.", minMinutes: 10, cost: 'free', energy: 'low', location: 'indoor', tags: ['productivity'] },
  { id: 60, text: "Find a free online course intro video on a topic you're curious about and watch the first lesson.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
];

if (typeof module !== 'undefined') module.exports = ACTIVITIES;
