// Activity dataset for Bored.
// Fields: id, text, minMinutes (time needed), cost: 'free'|'low'|'paid',
// energy: 'low'|'med'|'high', location: 'indoor'|'outdoor'|'any', tags: string[]
// tags[0] is treated as the primary category for display purposes.
const ACTIVITIES = [
  { id: 1, text: "Write down 3 things you're avoiding, then do the smallest one.", minMinutes: 5, cost: 'free', energy: 'low', location: 'any', tags: ['productivity'] },
  { id: 2, text: "Learn to say 'thank you' in a language you don't speak.", minMinutes: 5, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 3, text: "Do a 5-minute stretch: neck, shoulders, hips, hamstrings.", minMinutes: 5, cost: 'free', energy: 'med', location: 'any', tags: ['physical'] },
  { id: 4, text: "Text someone you haven't spoken to in 6+ months.", minMinutes: 5, cost: 'free', energy: 'low', location: 'any', tags: ['social'] },
  { id: 5, text: "Declutter one drawer completely.", minMinutes: 15, cost: 'free', energy: 'med', location: 'indoor', tags: ['chores'] },
  { id: 6, text: "Sketch the object nearest to you, badly, on purpose.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['creative'] },
  { id: 7, text: "Go for a walk with no destination for 15 minutes.", minMinutes: 15, cost: 'free', energy: 'med', location: 'outdoor', tags: ['physical', 'relaxation'] },
  { id: 8, text: "Cook something you've never made before using only what's in your kitchen.", minMinutes: 30, cost: 'free', energy: 'med', location: 'indoor', tags: ['creative', 'chores'] },
  { id: 9, text: "Read the Wikipedia 'On this day' page and pick a rabbit hole.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 10, text: "Do 20 push-ups (or a modified version). Rest 1 min. Do 20 more.", minMinutes: 10, cost: 'free', energy: 'high', location: 'any', tags: ['physical'] },
  { id: 11, text: "Write a one-star review of your own life as if it were a hotel. Make it funny.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['creative'] },
  { id: 12, text: "Call a family member and ask them a question you've never asked.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['social'] },
  { id: 13, text: "Reorganize your desktop/downloads folder into actual folders.", minMinutes: 20, cost: 'free', energy: 'med', location: 'indoor', tags: ['chores', 'productivity'] },
  { id: 14, text: "Learn 5 new words in a language you're studying (or start one).", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 15, text: "Do a 20-minute yoga video for beginners.", minMinutes: 20, cost: 'free', energy: 'med', location: 'indoor', tags: ['physical', 'relaxation'] },
  { id: 16, text: "Write a letter to your future self, one year from now. Set a reminder to reread it.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['creative', 'reflection'] },
  { id: 17, text: "Go outside and name 5 plants or birds you can see. Look up any you don't know.", minMinutes: 15, cost: 'free', energy: 'low', location: 'outdoor', tags: ['learning', 'relaxation'] },
  { id: 18, text: "Meal-prep lunch for tomorrow.", minMinutes: 30, cost: 'low', energy: 'med', location: 'indoor', tags: ['chores'] },
  { id: 19, text: "Try a 10-minute guided meditation.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['relaxation'] },
  { id: 20, text: "Fix one small annoying thing in your home you've been ignoring.", minMinutes: 20, cost: 'low', energy: 'med', location: 'indoor', tags: ['chores'] },
  { id: 21, text: "Watch a documentary trailer list and commit to watching one this week.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 22, text: "Go to a park and just sit for 20 minutes without your phone.", minMinutes: 20, cost: 'free', energy: 'low', location: 'outdoor', tags: ['relaxation'] },
  { id: 23, text: "Write a haiku about your current mood.", minMinutes: 5, cost: 'free', energy: 'low', location: 'any', tags: ['creative'] },
  { id: 24, text: "Do a 30-minute bike ride or run.", minMinutes: 30, cost: 'free', energy: 'high', location: 'outdoor', tags: ['physical'] },
  { id: 25, text: "Teach yourself a magic trick or a card shuffle technique.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['learning', 'creative'] },
  { id: 26, text: "Plan a day trip you'd actually want to take, even if you don't go yet.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['creative', 'reflection'] },
  { id: 27, text: "Deep clean your keyboard/phone/most-touched surface.", minMinutes: 10, cost: 'free', energy: 'low', location: 'indoor', tags: ['chores'] },
  { id: 28, text: "Try to name all the countries in a continent, then check your answers.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 29, text: "Visit a coffee shop or park you've never been to before.", minMinutes: 30, cost: 'low', energy: 'med', location: 'outdoor', tags: ['adventure'] },
  { id: 30, text: "Write down your 5-year plan in one paragraph. Don't overthink it.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['reflection'] },
  { id: 31, text: "Learn a new keyboard shortcut set for a tool you use daily.", minMinutes: 10, cost: 'free', energy: 'low', location: 'indoor', tags: ['productivity', 'learning'] },
  { id: 32, text: "Do a wall-sit for as long as you can, three times.", minMinutes: 10, cost: 'free', energy: 'high', location: 'any', tags: ['physical'] },
  { id: 33, text: "Look through old photos and pick your favorite from each of the last 5 years.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['reflection'] },
  { id: 34, text: "Write a short review of the last book, show, or game you finished.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['creative', 'reflection'] },
  { id: 35, text: "Take a cold shower and time how long you can handle it.", minMinutes: 5, cost: 'free', energy: 'high', location: 'indoor', tags: ['physical'] },
  { id: 36, text: "Draft an email you've been putting off. You don't have to send it yet.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['productivity'] },
  { id: 37, text: "Learn the rules of a board or card game you've never played.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 38, text: "Do a full-body 15-minute HIIT workout video.", minMinutes: 15, cost: 'free', energy: 'high', location: 'indoor', tags: ['physical'] },
  { id: 39, text: "Buy yourself something small and unnecessary that will make today better.", minMinutes: 20, cost: 'paid', energy: 'low', location: 'any', tags: ['adventure'] },
  { id: 40, text: "Try a new restaurant or cuisine you've never had.", minMinutes: 60, cost: 'paid', energy: 'low', location: 'outdoor', tags: ['adventure'] },
  { id: 41, text: "Go to a museum or gallery, even a small local one.", minMinutes: 60, cost: 'low', energy: 'med', location: 'outdoor', tags: ['adventure', 'learning'] },
  { id: 42, text: "Organize your notes app or to-do list into a system that actually works.", minMinutes: 30, cost: 'free', energy: 'med', location: 'indoor', tags: ['productivity'] },
  { id: 43, text: "Write the outline of a story, essay, or blog post idea you've had.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['creative'] },
  { id: 44, text: "Do a 20-minute dance session to a playlist you love. No one is watching.", minMinutes: 20, cost: 'free', energy: 'high', location: 'indoor', tags: ['physical', 'creative'] },
  { id: 45, text: "Look up one skill adjacent to your job that you don't have yet, and read about it.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['learning', 'productivity'] },
  { id: 46, text: "Give away or donate 5 items you haven't used in a year.", minMinutes: 20, cost: 'free', energy: 'med', location: 'indoor', tags: ['chores'] },
  { id: 47, text: "Plan and cook a proper meal from scratch, no shortcuts.", minMinutes: 60, cost: 'low', energy: 'med', location: 'indoor', tags: ['chores', 'creative'] },
  { id: 48, text: "Journal about the best part of your week so far.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['reflection'] },
  { id: 49, text: "Try a new stretch routine targeting the area that's tightest right now.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['physical', 'relaxation'] },
  { id: 50, text: "Look up a hiking trail nearby and go, even a short one.", minMinutes: 60, cost: 'free', energy: 'high', location: 'outdoor', tags: ['physical', 'adventure'] },
  { id: 51, text: "Write down every idea you've had this month that you never acted on.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['reflection', 'creative'] },
  { id: 52, text: "Practice a musical instrument you own but rarely touch.", minMinutes: 20, cost: 'free', energy: 'low', location: 'indoor', tags: ['creative'] },
  { id: 53, text: "Do 3 sets of squats, lunges, and planks.", minMinutes: 15, cost: 'free', energy: 'high', location: 'any', tags: ['physical'] },
  { id: 54, text: "Find a local event happening this week and consider going.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['social', 'adventure'] },
  { id: 55, text: "Watch a video essay or long-form talk on something outside your usual interests.", minMinutes: 30, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 56, text: "Wash your car, bike, or another neglected possession.", minMinutes: 30, cost: 'low', energy: 'med', location: 'outdoor', tags: ['chores'] },
  { id: 57, text: "Draft a 'not-to-do' list: 3 habits you want to stop this month.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['reflection', 'productivity'] },
  { id: 58, text: "Take yourself on a solo coffee or ice cream date.", minMinutes: 30, cost: 'low', energy: 'low', location: 'outdoor', tags: ['relaxation', 'adventure'] },
  { id: 59, text: "Fix your sleep setup: set tomorrow's alarm and lay out clothes tonight.", minMinutes: 10, cost: 'free', energy: 'low', location: 'indoor', tags: ['productivity'] },
  { id: 60, text: "Find a free online course intro video on a topic you're curious about and watch the first lesson.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 61, text: "Write down 3 people who've helped you this year and tell one of them why.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['social', 'reflection'] },
  { id: 62, text: "Do a 10-minute plank challenge: as many short holds as it takes to add up to 10 minutes.", minMinutes: 10, cost: 'free', energy: 'high', location: 'any', tags: ['physical'] },
  { id: 63, text: "Pick a photo you love and turn it into a 4-line poem.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['creative'] },
  { id: 64, text: "Clean out your inbox down to under 10 unread emails.", minMinutes: 30, cost: 'free', energy: 'med', location: 'indoor', tags: ['productivity', 'chores'] },
  { id: 65, text: "Learn how a piece of everyday tech actually works (e.g. how wifi routes data).", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 66, text: "Host a 15-minute video call with a friend you only text.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['social'] },
  { id: 67, text: "Rearrange one room's furniture to see if it flows better.", minMinutes: 30, cost: 'free', energy: 'high', location: 'indoor', tags: ['chores', 'creative'] },
  { id: 68, text: "Do 50 jumping jacks, rest 30 seconds, repeat 3 times.", minMinutes: 10, cost: 'free', energy: 'high', location: 'any', tags: ['physical'] },
  { id: 69, text: "Write a two-sentence pitch for a business you'll never start, just for fun.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['creative'] },
  { id: 70, text: "Find and fix one broken link or typo on something you've published (site, resume, doc).", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['productivity'] },
  { id: 71, text: "Try a breathing exercise: 4 seconds in, 7 hold, 8 out, for 2 minutes.", minMinutes: 5, cost: 'free', energy: 'low', location: 'any', tags: ['relaxation'] },
  { id: 72, text: "Take 10 minutes to research a place you'd like to visit someday.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['adventure', 'learning'] },
  { id: 73, text: "Go through your phone's camera roll and delete 50 photos you don't need.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['chores', 'productivity'] },
  { id: 74, text: "Write down the worst-case outcome of something you're worried about, then rate how likely it actually is.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['reflection'] },
  { id: 75, text: "Learn 3 chords on a guitar or 3 notes progression on a keyboard app.", minMinutes: 20, cost: 'free', energy: 'low', location: 'any', tags: ['creative', 'learning'] },
  { id: 76, text: "Do a lap of stairs (or a hill) 5 times.", minMinutes: 10, cost: 'free', energy: 'high', location: 'any', tags: ['physical'] },
  { id: 77, text: "Write a thank-you note to a teacher, mentor, or coworker who mattered.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['social', 'reflection'] },
  { id: 78, text: "Batch-schedule or cancel 3 recurring things draining your calendar.", minMinutes: 15, cost: 'free', energy: 'med', location: 'any', tags: ['productivity'] },
  { id: 79, text: "Try cooking one recipe from a cuisine you've never cooked before.", minMinutes: 45, cost: 'low', energy: 'med', location: 'indoor', tags: ['creative', 'chores'] },
  { id: 80, text: "Sit outside for 10 minutes and just watch what moves (clouds, traffic, birds).", minMinutes: 10, cost: 'free', energy: 'low', location: 'outdoor', tags: ['relaxation'] },
  { id: 81, text: "Look up one historical event that happened in your city and read about it.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['learning'] },
  { id: 82, text: "Do a posture check: reset your desk setup for the next hour of work.", minMinutes: 10, cost: 'free', energy: 'low', location: 'indoor', tags: ['productivity', 'physical'] },
  { id: 83, text: "Write a review — good or bad — for a small local business you actually visited.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['social'] },
  { id: 84, text: "Pick a skill you're mediocre at and do 15 minutes of deliberate practice on just the weakest part.", minMinutes: 15, cost: 'free', energy: 'med', location: 'any', tags: ['learning', 'productivity'] },
  { id: 85, text: "Go for a swim, even a short one.", minMinutes: 30, cost: 'low', energy: 'high', location: 'outdoor', tags: ['physical'] },
  { id: 86, text: "Make a paper airplane and try to beat your own distance record.", minMinutes: 10, cost: 'free', energy: 'med', location: 'any', tags: ['creative', 'physical'] },
  { id: 87, text: "Write down 3 boundaries you want to hold better this month.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['reflection'] },
  { id: 88, text: "Look up and try one new stretch or mobility drill for a joint that feels stiff.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['physical', 'relaxation'] },
  { id: 89, text: "Plan next week's meals in 10 minutes flat.", minMinutes: 10, cost: 'free', energy: 'low', location: 'indoor', tags: ['productivity', 'chores'] },
  { id: 90, text: "Take a photo walk: 20 minutes, phone camera only, look for good light.", minMinutes: 20, cost: 'free', energy: 'med', location: 'outdoor', tags: ['creative', 'adventure'] },
  { id: 91, text: "Write down one assumption about your work or life you've never questioned, then question it.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['reflection'] },
  { id: 92, text: "Try a 15-minute bodyweight circuit: squats, push-ups, lunges, plank, repeat.", minMinutes: 15, cost: 'free', energy: 'high', location: 'any', tags: ['physical'] },
  { id: 93, text: "Look up a free local class or meetup happening this month and consider signing up.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['social', 'adventure'] },
  { id: 94, text: "Back up your phone or laptop properly, for once.", minMinutes: 20, cost: 'free', energy: 'low', location: 'indoor', tags: ['productivity', 'chores'] },
  { id: 95, text: "Write a alternate ending to a movie or book you didn't like.", minMinutes: 15, cost: 'free', energy: 'low', location: 'any', tags: ['creative'] },
  { id: 96, text: "Go outside right after it rains and notice what smells and sounds different.", minMinutes: 10, cost: 'free', energy: 'low', location: 'outdoor', tags: ['relaxation'] },
  { id: 97, text: "Ask someone nearby a genuinely curious question about their day.", minMinutes: 5, cost: 'free', energy: 'low', location: 'any', tags: ['social'] },
  { id: 98, text: "List 5 skills you have that you take for granted.", minMinutes: 10, cost: 'free', energy: 'low', location: 'any', tags: ['reflection'] },
  { id: 99, text: "Try juggling with 3 soft objects for 10 minutes.", minMinutes: 10, cost: 'free', energy: 'med', location: 'any', tags: ['physical', 'creative'] },
  { id: 100, text: "Pick one app on your phone that wastes your time and delete it, right now.", minMinutes: 5, cost: 'free', energy: 'low', location: 'any', tags: ['productivity'] },
];

if (typeof module !== 'undefined') module.exports = ACTIVITIES;
